---
title: Paper title
csl: elsevier-harvard.csl
date: ''
output:
  html_document:
    css: resources/style.css
    pandoc_args:
    - +RTS
    - -K16000m
    - -RTS
    toc: yes
  pdf_document:
    toc: yes
fig_width: 4
fig_height: 2.6
bibliography: bibliography.bib
---


```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE, cache = FALSE}
# Packages
library(tidyverse)
library(knitr)
library(Hmisc)
library(brew)
library(maragra)
library(knitr)
library(googleVis)
library(RColorBrewer)
op <- options(gvis.plot.tag='chart')

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


<!-- <hr> -->
<!-- <p style="text-align:left;"> -->
<!-- [http://economicsofmalaria.com](http://economicsofmalaria.com) -->
<!-- <span style="float:right;">joebrew@gmail.com</span> -->
<!-- </p> -->
<!-- <hr> -->

```{r}
barplot(1:10)
```

# Introduction

Some text goes here

# Methods

Some text goes here

# Results

Some text goes here


# Discussion

Some text goes here



```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'knitr', 'rmarkdown'
), 'packages.bib')
```


# References

